---
title: "Basic Usage"
output: html_document
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)

p_load(tidyverse, ggridges)

library(themeBayer)
```

## List of Color Scales

### blue_green

```{r, echo = F}
ggplot(data = data.frame(bar = rep(1, 8), colors = c("#10384f", "#00617f",
    "#0091df", "#00bcff",
    "#004422", "#2b6636",
    "#66b512", "#89d329")), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'blue_green') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

### purple_green

```{r, echo = F}
ggplot(data = data.frame(colors = c(dark_purple, mid_purple, raspberry, fuchsia, light_green, green, mid_green, dark_green)), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'purple_green') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

### lights

```{r, echo = F}
ggplot(data = data.frame(colors = c(light_blue, light_green, fuchsia)), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'lights') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

### darks

```{r, echo = F}
ggplot(data = data.frame(colors =c(dark_blue, dark_green, dark_purple)), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'darks') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

### mids

```{r, echo = F}
ggplot(data = data.frame(colors =c(mid_blue, mid_green, mid_purple)), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'mids') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

### all

```{r, echo = F}
ggplot(data = data.frame(colors = c(dark_blue, dark_purple, dark_green, light_blue, fuchsia, light_green, blue, green, mid_purple, mid_green, mid_blue, raspberry)
), aes(x = colors, fill = colors)) + geom_bar() + themeBayer::scale_fill_bayer_d(name = 'all') + theme_minimal() + scale_y_discrete(labels = NULL, breaks = NULL) + labs(y = "", x = "") + theme(axis.text.x=element_blank())
```

## Plots

Continuous scales are not 'officially' approved, but can be generated by interpolated between existing points.

```{r cont-plot}
ggplot(data = cars, aes(x = speed, y = dist, color = dist)) + geom_point() + themeBayer::scale_color_bayer_c(name = 'purple_green') + theme_minimal()
```

## Discrete colors

```{r disc-plot}
## example uses very handy ggridges package

ggplot(data = iris, aes(x = Sepal.Length, y = Species, fill = Species)) + ggridges::geom_density_ridges(color = 'white', alpha = .4) + themeBayer::scale_fill_bayer_d(name = 'all', direction = -1) + theme_minimal()

## direction < 0 gives colors in reverse order
```
